typography_spectrum: 0.89149
color:
  brandColors:
    - '#ffffff'
    - '#050505'
    - '#505050'
    - '#b0b0b0'
    - '#e34e60'
  brandStrength: 0.8125
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.20409
analytics:
  google: null
  facebook: null
  twitter: null
name: "\_"
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: SHOWS
    id: c9257f9c-0b0a-4f80-82f1-87a0b480226f
    type: content
  - name: FACEBOOK
    url: 'https://www.facebook.com/trevorbahnsonmusic'
    type: external
  - name: BOOKING
    id: 11b8f19d-4113-459b-8272-168bb788e4e9
    type: content
favicon: null
title: TREVOR BAHNSON
purpose: []
