name: Trevor Bahnson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25962
title: TREVOR BAHNSON
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#454545'
    - '#e2e2e2'
    - '#666666'
    - '#8c8c8c'
  brandStrength: 0.6875
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
