name: trevorbahnson
favicon: null
layout_spectrum: 0.4438287417870015
typography_spectrum: 0.0791804997716099
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#fefdfe'
    - '#9c706b'
    - '#4b1b15'
    - '#cbc9d4'
  brandStrength: 0.698862929129973
  lightness: 0.3330559872556478
  saturation: 0.14847107836976647
  rhythmicContrast: 0.9699978001881391
purpose: []
