analytics: {}
color:
  brandColors:
    - '#050505'
    - '#454545'
    - '#e2e2e2'
    - '#666666'
    - '#8c8c8c'
  brandStrength: 0.6875
  lightness: 0.1875
  rhythmicContrast: 0.75
  saturation: 0.75
cta: {}
layout_spectrum: 0.388514
name: Trevor Bahnson
opengraph: {}
purpose: []
typography_spectrum: 0.305743
