name: Trevor Bahnson
favicon: null
layout_spectrum: 0.72162
typography_spectrum: 1
title: TREVOR BAHNSON
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050505'
    - '#505050'
    - '#b0b0b0'
    - '#e34e60'
  brandStrength: 0.8125
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
