name: Trevor Bahnson
favicon: null
layout_spectrum: 0.72162
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#454545'
    - '#e2e2e2'
    - '#666666'
    - '#8c8c8c'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
