name: trevorbahnson
favicon: null
layout_spectrum: 0.4438287417870015
typography_spectrum: 0.0791804997716099
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.698862929129973
  lightness: 0.3330559872556478
  saturation: 0.14847107836976647
  rhythmicContrast: 0.9699978001881391
purpose: []
